# Generated by Django 4.2.10 on 2024-05-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_pic',
            field=models.ImageField(blank=True, upload_to='category/'),
        ),
    ]
