# Generated by Django 4.2.10 on 2024-05-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_featuredcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredpost',
            name='pic',
            field=models.ImageField(blank=True, upload_to='featuredpic/'),
        ),
    ]
