# Generated by Django 4.2.10 on 2024-03-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
