# Generated by Django 4.2.10 on 2024-04-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.CharField(blank=True, choices=[('modir', 'modir'), ('dabir', 'dabir'), ('moaven dabir', 'moaven dabir'), ('khazane dar', 'khazane dar'), ('ozv mamoli', 'ozv mamoli')], max_length=50, verbose_name='نقش'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='user/profile/', verbose_name='profile'),
        ),
    ]
